<?php

/**
 * X-01: extends the Permission module's coverage to routes that aren't a
 * `module_pages` row themselves (background/AJAX endpoints a page's UI
 * calls — list-data, save, delete, download — rather than the page load
 * itself). Common::checkRouteWisePermission() checks this map only after
 * module_pages has no entry for the route.
 *
 * Format: 'route.name' => ['owner_page_internal_route', 'required_tick']
 *   - owner_page_internal_route: a module_pages.internal_route this route's
 *     access should follow (usually the parent page's route name).
 *   - required_tick: 'view' | 'create' | 'edit' | 'delete' — which
 *     Permissions-screen tick gates this specific route. GET/list/download
 *     endpoints are normally 'view'; store/update 'edit' or 'create';
 *     destroy 'delete'.
 *   - ['*', 'any_authenticated'] — every logged-in portal user may call it
 *     (own-profile/notification/global-search style routes; use sparingly).
 *
 * A route present in neither module_pages nor this map is currently
 * report-only: Common::checkRouteWisePermission() logs it
 * (Log::warning('UNMAPPED_ROUTE', ...)) and still allows it — unchanged
 * behavior, so adding this file breaks nothing on its own. Flip
 * 'enforce_unmapped' below to true only after the report-only log has run
 * against real traffic long enough to add every legitimate gap here first
 * (see the recommended rollout in SECURITY_AUDIT_REMAINING.md's X-01 entry
 * — a sudden switch to deny-by-default is an outage risk, not a quick flag
 * flip).
 *
 * This is a starting set (the routes named in this session's own fixes,
 * where an in-method role check already exists — this map is the outer
 * lock, that check is the inner one, per the audit's own two-layer model).
 * Extending it to the other ~1,370 currently-unmapped routes is follow-up
 * work; storage/app/unprotected_routes.txt (generated by the read-only
 * diagnostic in X-01's audit entry) has the full current list.
 */

return [

    'enforce_unmapped' => false,

    'map' => [

        // Talent Acquisition — applicant document access / destructive actions
        // (ApplicantsController, gated in-method via requireHrAccess() — T-05)
        'resort.ta.DownloadFile'            => ['resort.vacancies.FreshApplicant', 'view'],
        'resort.ta.DownloadAllFiles'        => ['resort.vacancies.FreshApplicant', 'view'],
        'resort.ta.DownloadAllFilesZip'     => ['resort.vacancies.FreshApplicant', 'view'],
        'resort.ta.destoryApplicant'        => ['resort.vacancies.FreshApplicant', 'delete'],
        'resort.ta.deleteTalentPoolApplicant' => ['resort.ta.TalentPool', 'delete'],
        'resort.ta.sendOfferLetter'         => ['resort.vacancies.FreshApplicant', 'edit'],
        'resort.ta.sendContract'            => ['resort.vacancies.FreshApplicant', 'edit'],
        'resort.ta.saveSalaryAllocation'    => ['resort.vacancies.FreshApplicant', 'edit'],
        'interview-assessment.update'       => ['interview-assessment.index', 'edit'],

        // Performance — KPI approval, PIP/PDP, cycle delete, review export
        // (gated in-method — PF-02/PF-03/PF-04/PF-05). KPI/PIP/PDP don't
        // have their own module_pages row at all (only Hrdashboard/
        // Meeting.index/cycle/configuration/MonltyCheckIn are registered
        // for this module) — pointed at the closest real registered page
        // (Performance.cycle) rather than a page name that doesn't exist;
        // give KPI/PIP/PDP their own module_pages rows as a follow-up.
        'Performance.config.ReviewTypes.inlineUpdate' => ['Performance.configuration', 'edit'],
        'Performance.kpi.approve'    => ['Performance.cycle', 'edit'],
        'Performance.kpi.reject'     => ['Performance.cycle', 'edit'],
        'Performance.pip.store'      => ['Performance.cycle', 'create'],
        'Performance.pip.archive'    => ['Performance.cycle', 'delete'],
        'Performance.pip.restore'    => ['Performance.cycle', 'edit'],
        'Performance.pdp.store'      => ['Performance.cycle', 'create'],
        'Performance.pdp.archive'    => ['Performance.cycle', 'delete'],
        'Performance.pdp.restore'    => ['Performance.cycle', 'edit'],
        'Performance.cycle.destory'  => ['Performance.cycle', 'delete'],
        'Performance.Review.gmExport' => ['Performance.cycle', 'view'],

        // SOS — destructive/broad actions (gated in-method — SO-02)
        'sos.emergency.destroy'        => ['sos.dashboard.index', 'delete'],
        'sos.emergency.update.status'  => ['sos.dashboard.index', 'edit'],
        'sos.updateMassInstruction'    => ['sos.dashboard.index', 'edit'],

    ],

];
