<?php
return [
	'site_logo_folder' => 'public/uploads/logos',
	'site_favicon_folder' => 'public/uploads/favicon',
	'auth_sign_folder' => 'public/uploads/signs',
	'default_picture' => 'admin_assets/files/user-image.png',
	'default_picture2' => 'admin_assets/files/default-pic.jpg',
    'Nodatafoundimage' => 'admin_assets/files/Nodatafound.jfif',
	'admin_folder' => 'public/uploads/admins',
	'customer_folder' => 'public/uploads/customers',
	'admin_picture_folder' => 'public/uploads/admin_pictures',
	'user_picture_folder' => 'public/uploads/users',
	'purchaseorder_folder' => 'public/uploads/purchaseorder',
	'resort_admin_folder'  => 'public/uploads/resort_admins',
	'brand_logo_folder' => 'public/uploads/brand_logos',
	'ResortProfile_folder' => 'uploads/resortprofile',
	'Resort_BudgetConfigFiles' => 'public/uploads/BudgetConfigFiles',
	'Resort_EmployeeProfile' => 'public/uploads/Resort_EmployeeProfile',
	'Resort_SiteSettings' => 'public/uploads/Resort_SiteSettings',
    'Resort_currency' =>'resorts_assets/images',
    'Resort_ApplicantsFolder' =>'resorts_assets/Applicants',
    'Resort_JobAdvertisement' =>'resorts_assets/JobAdvertisement',
	'Resortsignature_folder' => 'public/uploads/Resortsignature_folder',
	'Resort_Applicant' =>'public/uploads/Applicant',
	// 'leave_attachments' =>'public/uploads/leave_attachments',
	'leave_attachments' =>'uploads/leave_attachments',
	'Resort_Holidays' =>'public/uploads/Holidays',
	// 'Employees_Document' =>'public/uploads/EmployeesDocument',
	'Employees_Document' =>'uploads/EmployeesDocument',
    'MaintanceRequest' =>'uploads/MaintanceRequest',
	'city_ladger_file' => 'public/uploads/city_ladger_file',
	'GrievanceSubmission' => 'public/uploads/GrievanceSubmission',
	'Housekeeping_Images'=>	'uploads/HousekeepingImages',
	'support_ticket_attachments' => 'uploads/support_ticket_attachments',
	'chat_attachments' => 'uploads/chat_attachments',
	'PayslipPdf' => 'uploads/payslip',
	'incident_meeting_attachments' => 'uploads/incident_meeting_attachments',
	'incident_attatchements' => 'uploads/incident_attatchements',
	'incident_statements' => 'uploads/incident_statements',
	'GrivanceAttachments' =>'uploads/GrivanceAttachments',
	'DisciplinaryAttachments' =>'uploads/DisciplinaryAttachments',
	'employee_biometrics' => 'uploads/employee_biometrics',
	'ShopkeeperProfile_folder' => 'uploads/shopkeeper_profile',
	'employee_certificates'=>'uploads/employee_certificates',
	'employee_exp_letters'=>'uploads/employee_exp_letters',
	'Manifestdetailspdf' => 'uploads/ManifestPDF',
	'clinicAttachments' => 'uploads/clinic_attachments',
	'clinicTreatmentAttachments' => 'uploads/clinic_treatment_attachments',
	'clinicMedicalCertificateAttachments' => 'uploads/clinic_medical_certificate',
	'RequestAttachments' => 'uploads/request_attachments',
	'FundTransfer' => 'uploads/FundTransfer',
	'ExitClearanceAttachments' => 'uploads/exit_clearance_attachments',
	'ResignationAttachments' => 'uploads/resignation_attachments',
	'experienceLetters' => 'uploads/experience_letters',
	'employeeSelfie' => 'public/uploads/employee_selfie',
	'jd_path' => 'public/uploads/jobdiscription',


	'superadmin_email' => env('SUPERADMIN_EMAIL', 'supportwai@yopmail.com'),

	'permissions' => [
		'view' => 1,
		'create' => 2,
		'edit' => 3,
		'delete' => 4,
	],

	'resort_permissions' => [
		'view' => 1,
		'create' => 2,
		'edit' => 3,
		'delete' => 4,
		// 'self' => 5,
		// 'assign' => 6,
		// 'approve' => 7,
	],

	'admin_modules' => [
		'admin_users' => 1,
		'settings' => 2,
		'roles_permissions' => 3,
		'email_templates' => 4,
		'resorts' =>5,
		'divisions'=> 6,
		'departments'=> 7,
		'sections' => 8,
		'positions' => 9,
		'notifications' => 10,
        'modules' => 11,
        'Pages'=>12,
		'public_holidays'=>13,
		'ewt_brackets'=>14,
		'support_categories'=>15,
		'supports'=>16

	],

	'levels' => [
		'Beginner',
		'Advanced',
	],

   'countries' => [
	'AF' => 'Afghanistan',
	'AX' => 'Aland Islands',
	'AL' => 'Albania',
	'DZ' => 'Algeria',
	'AS' => 'American Samoa',
	'AD' => 'Andorra',
	'AO' => 'Angola',
	'AI' => 'Anguilla',
	'AQ' => 'Antarctica',
	'AG' => 'Antigua And Barbuda',
	'AR' => 'Argentina',
	'AM' => 'Armenia',
	'AW' => 'Aruba',
	'AU' => 'Australia',
	'AT' => 'Austria',
	'AZ' => 'Azerbaijan',
	'BS' => 'Bahamas',
	'BH' => 'Bahrain',
	'BD' => 'Bangladesh',
	'BB' => 'Barbados',
	'BY' => 'Belarus',
	'BE' => 'Belgium',
	'BZ' => 'Belize',
	'BJ' => 'Benin',
	'BM' => 'Bermuda',
	'BT' => 'Bhutan',
	'BO' => 'Bolivia',
	'BA' => 'Bosnia And Herzegovina',
	'BW' => 'Botswana',
	'BV' => 'Bouvet Island',
	'BR' => 'Brazil',
	'IO' => 'British Indian Ocean Territory',
	'BN' => 'Brunei Darussalam',
	'BG' => 'Bulgaria',
	'BF' => 'Burkina Faso',
	'BI' => 'Burundi',
	'KH' => 'Cambodia',
	'CM' => 'Cameroon',
	'CA' => 'Canada',
	'CV' => 'Cape Verde',
	'KY' => 'Cayman Islands',
	'CF' => 'Central African Republic',
	'TD' => 'Chad',
	'CL' => 'Chile',
	'CN' => 'China',
	'CX' => 'Christmas Island',
	'CC' => 'Cocos (Keeling) Islands',
	'CO' => 'Colombia',
	'KM' => 'Comoros',
	'CG' => 'Congo',
	'CD' => 'Congo, Democratic Republic',
	'CK' => 'Cook Islands',
	'CR' => 'Costa Rica',
	'CI' => 'Cote D\'Ivoire',
	'HR' => 'Croatia',
	'CU' => 'Cuba',
	'CY' => 'Cyprus',
	'CZ' => 'Czech Republic',
	'DK' => 'Denmark',
	'DJ' => 'Djibouti',
	'DM' => 'Dominica',
	'DO' => 'Dominican Republic',
	'EC' => 'Ecuador',
	'EG' => 'Egypt',
	'SV' => 'El Salvador',
	'GQ' => 'Equatorial Guinea',
	'ER' => 'Eritrea',
	'EE' => 'Estonia',
	'ET' => 'Ethiopia',
	'FK' => 'Falkland Islands (Malvinas)',
	'FO' => 'Faroe Islands',
	'FJ' => 'Fiji',
	'FI' => 'Finland',
	'FR' => 'France',
	'GF' => 'French Guiana',
	'PF' => 'French Polynesia',
	'TF' => 'French Southern Territories',
	'GA' => 'Gabon',
	'GM' => 'Gambia',
	'GE' => 'Georgia',
	'DE' => 'Germany',
	'GH' => 'Ghana',
	'GI' => 'Gibraltar',
	'GR' => 'Greece',
	'GL' => 'Greenland',
	'GD' => 'Grenada',
	'GP' => 'Guadeloupe',
	'GU' => 'Guam',
	'GT' => 'Guatemala',
	'GG' => 'Guernsey',
	'GN' => 'Guinea',
	'GW' => 'Guinea-Bissau',
	'GY' => 'Guyana',
	'HT' => 'Haiti',
	'HM' => 'Heard Island & Mcdonald Islands',
	'VA' => 'Holy See (Vatican City State)',
	'HN' => 'Honduras',
	'HK' => 'Hong Kong',
	'HU' => 'Hungary',
	'IS' => 'Iceland',
	'IN' => 'India',
	'ID' => 'Indonesia',
	'IR' => 'Iran, Islamic Republic Of',
	'IQ' => 'Iraq',
	'IE' => 'Ireland',
	'IM' => 'Isle Of Man',
	'IL' => 'Israel',
	'IT' => 'Italy',
	'JM' => 'Jamaica',
	'JP' => 'Japan',
	'JE' => 'Jersey',
	'JO' => 'Jordan',
	'KZ' => 'Kazakhstan',
	'KE' => 'Kenya',
	'KI' => 'Kiribati',
	'KR' => 'Korea',
	'KW' => 'Kuwait',
	'KG' => 'Kyrgyzstan',
	'LA' => 'Lao People\'s Democratic Republic',
	'LV' => 'Latvia',
	'LB' => 'Lebanon',
	'LS' => 'Lesotho',
	'LR' => 'Liberia',
	'LY' => 'Libyan Arab Jamahiriya',
	'LI' => 'Liechtenstein',
	'LT' => 'Lithuania',
	'LU' => 'Luxembourg',
	'MO' => 'Macao',
	'MK' => 'Macedonia',
	'MG' => 'Madagascar',
	'MW' => 'Malawi',
	'MY' => 'Malaysia',
	'MV' => 'Maldives',
	'ML' => 'Mali',
	'MT' => 'Malta',
	'MH' => 'Marshall Islands',
	'MQ' => 'Martinique',
	'MR' => 'Mauritania',
	'MU' => 'Mauritius',
	'YT' => 'Mayotte',
	'MX' => 'Mexico',
	'FM' => 'Micronesia, Federated States Of',
	'MD' => 'Moldova',
	'MC' => 'Monaco',
	'MN' => 'Mongolia',
	'ME' => 'Montenegro',
	'MS' => 'Montserrat',
	'MA' => 'Morocco',
	'MZ' => 'Mozambique',
	'MM' => 'Myanmar',
	'NA' => 'Namibia',
	'NR' => 'Nauru',
	'NP' => 'Nepal',
	'NL' => 'Netherlands',
	'AN' => 'Netherlands Antilles',
	'NC' => 'New Caledonia',
	'NZ' => 'New Zealand',
	'NI' => 'Nicaragua',
	'NE' => 'Niger',
	'NG' => 'Nigeria',
	'NU' => 'Niue',
	'NF' => 'Norfolk Island',
	'MP' => 'Northern Mariana Islands',
	'NO' => 'Norway',
	'OM' => 'Oman',
	'PK' => 'Pakistan',
	'PW' => 'Palau',
	'PS' => 'Palestinian Territory, Occupied',
	'PA' => 'Panama',
	'PG' => 'Papua New Guinea',
	'PY' => 'Paraguay',
	'PE' => 'Peru',
	'PH' => 'Philippines',
	'PN' => 'Pitcairn',
	'PL' => 'Poland',
	'PT' => 'Portugal',
	'PR' => 'Puerto Rico',
	'QA' => 'Qatar',
	'RE' => 'Reunion',
	'RO' => 'Romania',
	'RU' => 'Russian Federation',
	'RW' => 'Rwanda',
	'BL' => 'Saint Barthelemy',
	'SH' => 'Saint Helena',
	'KN' => 'Saint Kitts And Nevis',
	'LC' => 'Saint Lucia',
	'MF' => 'Saint Martin',
	'PM' => 'Saint Pierre And Miquelon',
	'VC' => 'Saint Vincent And Grenadines',
	'WS' => 'Samoa',
	'SM' => 'San Marino',
	'ST' => 'Sao Tome And Principe',
	'SA' => 'Saudi Arabia',
	'SN' => 'Senegal',
	'RS' => 'Serbia',
	'SC' => 'Seychelles',
	'SL' => 'Sierra Leone',
	'SG' => 'Singapore',
	'SK' => 'Slovakia',
	'SI' => 'Slovenia',
	'SB' => 'Solomon Islands',
	'SO' => 'Somalia',
	'ZA' => 'South Africa',
	'GS' => 'South Georgia And Sandwich Isl.',
	'ES' => 'Spain',
	'LK' => 'Sri Lanka',
	'SD' => 'Sudan',
	'SR' => 'Suriname',
	'SJ' => 'Svalbard And Jan Mayen',
	'SZ' => 'Swaziland',
	'SE' => 'Sweden',
	'CH' => 'Switzerland',
	'SY' => 'Syrian Arab Republic',
	'TW' => 'Taiwan',
	'TJ' => 'Tajikistan',
	'TZ' => 'Tanzania',
	'TH' => 'Thailand',
	'TL' => 'Timor-Leste',
	'TG' => 'Togo',
	'TK' => 'Tokelau',
	'TO' => 'Tonga',
	'TT' => 'Trinidad And Tobago',
	'TN' => 'Tunisia',
	'TR' => 'Turkey',
	'TM' => 'Turkmenistan',
	'TC' => 'Turks And Caicos Islands',
	'TV' => 'Tuvalu',
	'UG' => 'Uganda',
	'UA' => 'Ukraine',
	'AE' => 'United Arab Emirates',
	'GB' => 'United Kingdom',
	'US' => 'United States',
	'UM' => 'United States Outlying Islands',
	'UY' => 'Uruguay',
	'UZ' => 'Uzbekistan',
	'VU' => 'Vanuatu',
	'VE' => 'Venezuela',
	'VN' => 'Viet Nam',
	'VG' => 'Virgin Islands, British',
	'VI' => 'Virgin Islands, U.S.',
	'WF' => 'Wallis And Futuna',
	'EH' => 'Western Sahara',
	'YE' => 'Yemen',
	'ZM' => 'Zambia',
	'ZW' => 'Zimbabwe',
	],

	'resort_modules' => [
		'workforce_planning' => 1,
		'budget/payroll' => 2,
		'talent_acquisition' => 3,
		'people' => 4,
		'time_and_attendance' => 5,
		'leave' => 6,
		'performance' => 7,
		'disciplinary' => 8,
		'learning' => 9,
		'accommodation' => 10,
		'pension' => 12,
		'incident' => 13,
		'talent_pool' => 14,
		'survey' => 15,
		'reports' => 16,
		'audit' => 17,
		'documents' => 18,
		'billing' => 19,
		'visa' => 20,
		'security' => 21,
		'special_features' => 22,
		'settings' => 23,
		'resort_profile' => 24,
		'roles_permissions' => 25,
	],

	'email_types' => [
		'email_verification' => 1,
		'reset_password' => 2,
		'reset_password_notification' => 3,
		'change_password_notification' => 4,
		'welcome_email' => 8,
		'email_otp_verification' => 9,
		'email_verify_success_notification' => 10,
		'forgot_password_otp' => 11
	],

	'status' => [
        'active' => 'Active',
        'inactive' => 'Inactive',
    ],
    'payment_status' => [
        'paid' => 'Paid',
        'unpaid' => 'Unpaid',
        'partial' => 'Partially Paid',
    ],
    'invoice_status' => [
        'draft' => 'Draft',
        'sent' => 'Sent',
        'paid' => 'Paid',
    ],
	'service_packages'=> [
        'package1' => 'Package 1',
        'package2' => 'Package 2',
        'package3' => 'Package 3',
    ],
	'support_channels'=>[
		'email'=> 'Email',
		'phone' => 'Phone',
		'livechat' => 'LiveChat'
	],

	'email_log_associate_types' => [
	],

	'email_log_associate_types_reverse' =>[
	],

	'email_template' => [
		'password_reset_email' => 1,
		'password_change_notification' => 2,
		'resort_registration_notification' => 3,
		'admin_registration_notification' => 4,
		'new_leave_date_recommendation' => 5,
		'travel_arrangement_for_employee'=> 6,
		'shopkeeper_registration_notification'=> 7,
		'consent_product_purchase_notification'=> 8,
		'share_pay_slip' => 9,
		'support_email' => 10,
		'support_reply_email'=>11
	],

	'user_types' => [
		'admin' => 'A',
		'employee' => 'E',
		'customer'=> 'U'
	],

	'user_types_reverse' => [
		'A' => 'Admin',
		'E' => 'Employee',
		'U' => 'Customer'
	],

	'route_prefix' => [
		'admin' => '/admin',
		'user' => '/user',
		'customer' => '/customer'
	],

	'date_formats' => [
		'Y-m-d',
		'm-d-Y',
		'd-m-Y',
		'd/m/Y',
		'm/d/Y'
	],

	'time_formats' => [
		'12',
		'24'
	],

	'currency' => [
        "MVR"=>"MVR",
        "Dollar"=>"Dollar",
        // "Euro" => "Euro",
	],

	'days' => [
		'Sunday',
		'Monday',
		'Tuesday',
		'Wednesday',
		'Thursday',
		'Friday',
		'Saturday',
	],

    'Notifications'=>[
        '1', //"SuperAdmin To Resort",
        '2', //"resort Hr To Resort Department",
        '3',//"resort Reminder Request Sent Department who had not submitted manning",
        '4',// When hod will send the manning budget request then the specific hr Dasboard will be notified and update the pending department list
        '5',// When Hr Review Done sent to Finance Department
        '6',// When Hr Review and sent Review Budget for department
        '7',// When Talent Acquisition Hod Send Vacanincy request to HR
        '8',// When Hr Review Done sent to Finance Department
        '9',//When finance is approved and sent to GM/Corporate Office
		'10',// Common resort internal notification to  employees e.g birthday notifiction, learning request notification
		'11',// conscent approval notification yo employee from shopkeeper - payroll module

    ],

    // Manning Request MSG

    'manning_request' => [
        'msg1'=>'This is a Manning Request for additional manpower requirements. Please review and update your response accordingly.',
        'msg2'=>'This reminder massage. Please Submit Your Manning Request. Thank You.',
        'msg3'=>'Please Revise Your manning request and Submit.',
    ],

    'manning_request_status' => [
        'pending' => 'Pending',
        'accepted' => 'Accepted',
        'declined' => 'Declined',
    ],

    'manningRequestLifeCycle' => [
        'Respond to HR',
        'Reviewed by HR and Sent to Finance',
        'Revise Budget',
        'Reviewed by Finance and Sent to GM/Corporate Office',
        'Approved by GM/Corporate Office'
    ],

	// 'Position_Rank' => [
    //     '1' => 'EXCOM',
    //     '2' => 'HOD',
    //     '3' => 'HR',
    //     '4' => 'MGR',
    //     '5' => 'SUP',
    //     '6' => 'LINE WORKERS',
    //     '7' => 'Finance',
    //     '8' => 'GM',
    //     '9' => 'MD',
    //     '10' => 'SO',
    //     '11' => 'EDHOD', //Engineering Department Head
    //     '12' => 'CLINIC_STAFF', // Clinic Staff
    // ],
	'EscalationDay' => 3,


	'Position_Rank' => [
        '8' => 'GM',
		'1' => 'EXCOM',
        '2' => 'HOD',
		'3' => 'HR',
		'4' => 'MGR',
        '5' => 'SUP',
        '6' => 'LINE WORKERS',
		'7' => 'Finance',
    ],

	'final_rank' => [
		'3' => 'HR', // Done
		'7' => 'Finance', // Done
		'8' => 'GM',       // Done
		// '9' => 'Corporate Office' // To Do
	],

    'InterViewRound' => [
        '3' => 'HR',
        '2' => 'HOD',
        '8' => 'GM',
        // '9' => 'GM Select',
	],

	'eligibilty' => [
		'8' => 'GM',
		'1' => 'EXCOM',
        '2' => 'HOD',
		'4' => 'MGR',
        '5' => 'SUP',
        '6' => 'LINE WORKERS',
	],

    'budget_process_role' => [
        '1'=>"HOD",
        '2'=>"HR",
        '3'=>"Finance",
        '4'=>"GM",
    ],

    'ResortTimeZone'=>'Indian/Maldives',
    'ResortstringTime' =>'9:00 AM',
    'ResortEndingTime' =>'5:00 PM',

	'Transportations' => [
		'1' => "Seaplane",
		'2' => "Speedboat",
		'3' => "Domestic Flight",
		'4'  => "International Flight",
	],

	'ReverseTransportations' => [
		'seaplane' => 1,
        'speedboat' => 2,
        'domestic_flight' => 3,
        'international_flight' => 4,
	],

	'DisciplinaryApprovalRole'
	=> [
		'1' => "Suspension",
		'2' => "Dismissal",
		'3' => "Appeals",
	],
    'CleaningSchedule' => ['Daily', 'Weekly', 'ByWeekly', 'Monthly'],
    'RoomStatus' => ['Available', 'Occupied', 'Under Maintenance', 'Maintenance Required', 'Under Maintenance', 'Not in Operation'],
    'EmployeeStatus' => ['Active', 'OnLeave','Probationary','Terminated','Retired','Resigned','Suspended','transferred','contractual'],
    'GenderType' => [
		'Male', 'Female','Other'
	],
	'notificationTiming' =>	[
		'Immidiate' => 'Immidiate',
		'1 Day Before' => '1 Day Before',
		'2 Days Before' => '2 Days Before',
		'3 Days Before' => '3 Days Before',
		'1 Hours Before' => '1 Hours Before',
		'2 Hours Before' => '2 Hours Before',
		'3 Hours Before' => '3 Hours Before',
		'1 Hours After' => '1 Hours After',
		'2 Hours After' => '2 Hours After',
		'3 Hours After' => '3 Hours After',
	],

	'nationalities' => [
			"Afghan",
			"Albanian",
			"Algerian",
			"American",
			"Andorran",
			"Angolan",
			"Antiguan and Barbudan",
			"Argentine",
			"Armenian",
			"Australian",
			"Austrian",
			"Azerbaijani",
			"Bahamian",
			"Bahraini",
			"Bangladeshi",
			"Barbadian",
			"Belarusian",
			"Belgian",
			"Belizean",
			"Beninese",
			"Bhutanese",
			"Bolivian",
			"Bosnian and Herzegovinian",
			"Botswanan",
			"Brazilian",
			"British",
			"Bruneian",
			"Bulgarian",
			"Burkinabé",
			"Burmese",
			"Burundian",
			"Cambodian",
			"Cameroonian",
			"Canadian",
			"Cape Verdean",
			"Central African",
			"Chadian",
			"Chilean",
			"Chinese",
			"Colombian",
			"Comorian",
			"Congolese (Congo-Brazzaville)",
			"Congolese (Congo-Kinshasa)",
			"Costa Rican",
			"Croatian",
			"Cuban",
			"Cypriot",
			"Czech",
			"Danish",
			"Djiboutian",
			"Dominican",
			"Dutch",
			"East Timorese",
			"Ecuadorean",
			"Egyptian",
			"Emirati",
			"Equatorial Guinean",
			"Eritrean",
			"Estonian",
			"Eswatini",
			"Ethiopian",
			"Fijian",
			"Filipino",
			"Finnish",
			"French",
			"Gabonese",
			"Gambian",
			"Georgian",
			"German",
			"Ghanaian",
			"Greek",
			"Grenadian",
			"Guatemalan",
			"Guinean",
			"Bissau-Guinean",
			"Guyanese",
			"Haitian",
			"Honduran",
			"Hungarian",
			"Icelander",
			"Indian",
			"Indonesian",
			"Iranian",
			"Iraqi",
			"Irish",
			"Israeli",
			"Italian",
			"Ivorian",
			"Jamaican",
			"Japanese",
			"Jordanian",
			"Kazakhstani",
			"Kenyan",
			"Kiribati",
			"Kuwaiti",
			"Kyrgyzstani",
			"Lao",
			"Latvian",
			"Lebanese",
			"Liberian",
			"Libyan",
			"Liechtensteiner",
			"Lithuanian",
			"Luxembourger",
			"Malagasy",
			"Malawian",
			"Malaysian",
			"Maldivian",
			"Malian",
			"Maltese",
			"Marshallese",
			"Mauritanian",
			"Mauritian",
			"Mexican",
			"Micronesian",
			"Moldovan",
			"Monacan",
			"Mongolian",
			"Montenegrin",
			"Moroccan",
			"Mozambican",
			"Namibian",
			"Nauruan",
			"Nepalese",
			"New Zealander",
			"Nicaraguan",
			"Nigerien",
			"Nigerian",
			"North Korean",
			"North Macedonian",
			"Norwegian",
			"Omani",
			"Pakistani",
			"Palauan",
			"Palestinian",
			"Panamanian",
			"Papua New Guinean",
			"Paraguayan",
			"Peruvian",
			"Polish",
			"Portuguese",
			"Qatari",
			"Romanian",
			"Russian",
			"Rwandan",
			"Saint Kitts and Nevisian",
			"Saint Lucian",
			"Saint Vincentian",
			"Samoan",
			"San Marinese",
			"São Toméan",
			"Saudi Arabian",
			"Senegalese",
			"Serbian",
			"Seychellois",
			"Sierra Leonean",
			"Singaporean",
			"Slovak",
			"Slovenian",
			"Solomon Islander",
			"Somali",
			"South African",
			"South Korean",
			"South Sudanese",
			"Spanish",
			"Sri Lankan",
			"Sudanese",
			"Surinamese",
			"Swedish",
			"Swiss",
			"Syrian",
			"Tajikistani",
			"Tanzanian",
			"Thai",
			"Togolese",
			"Tongan",
			"Trinidadian and Tobagonian",
			"Tunisian",
			"Turkish",
			"Turkmen",
			"Tuvaluan",
			"Ugandan",
			"Ukrainian",
			"Uruguayan",
			"Uzbekistani",
			"Vanuatuan",
			"Vatican Citizen",
			"Venezuelan",
			"Vietnamese",
			"Yemeni",
			"Zambian",
			"Zimbabwean"
	],
		'Footer' => 'Copyright © ' . date("Y") . '. All Rights Reserved.',

	'sosAssignPermissions' => [
		'1' => 'Acknowledge SOS', //Sos details
		'2' => 'Approve or reject SOS requests', // Security-Manager-Sos
	],

	'VisaCategory' => [
		'Insurance' => 'Insurance',
		'Passport_Copy' => 'Passport Copy',
		'Work_Permit_Entry_Pass' => 'Work Permit Entry Pass',
		'Visa' => 'Visa',
		'Work_Permit_Card' => 'Work Permit Card',
		'Medical_Report' => 'Medical Report',
	],

	'foreign_languages' => [
		'Afrikaans' => 'Afrikaans - South Africa',
		'Albanian' => 'Albanian - Albania',
		'Amharic' => 'Amharic - Ethiopia',
		'Arabic' => 'Arabic - Middle East',
		'Armenian' => 'Armenian - Armenia',
		'Azerbaijani' => 'Azerbaijani - Azerbaijan',
		'Basque' => 'Basque - Spain',
		'Belarusian' => 'Belarusian - Belarus',
		'Bengali' => 'Bengali - Bangladesh / India',
		'Bosnian' => 'Bosnian - Bosnia',
		'Bulgarian' => 'Bulgarian - Bulgaria',
		'Burmese' => 'Burmese - Myanmar',
		'Catalan' => 'Catalan - Spain',
		'Cebuano' => 'Cebuano - Philippines',
		'Chinese (Mandarin)' => 'Chinese (Mandarin) - China',
		'Chinese (Cantonese)' => 'Chinese (Cantonese) - Hong Kong',
		'Croatian' => 'Croatian - Croatia',
		'Czech' => 'Czech - Czech Republic',
		'Danish' => 'Danish - Denmark',
		'Dhivehi' => 'Dhivehi - Maldives',
		'Dutch' => 'Dutch - Netherlands',
		'English' => 'English - USA / UK / Australia',
		'Estonian' => 'Estonian - Estonia',
		'Filipino (Tagalog)' => 'Filipino (Tagalog) - Philippines',
		'Finnish' => 'Finnish - Finland',
		'French' => 'French - France',
		'Galician' => 'Galician - Spain',
		'Georgian' => 'Georgian - Georgia',
		'German' => 'German - Germany',
		'Greek' => 'Greek - Greece',
		'Gujarati' => 'Gujarati - India',
		'Haitian Creole' => 'Haitian Creole - Haiti',
		'Hausa' => 'Hausa - Nigeria',
		'Hebrew' => 'Hebrew - Israel',
		'Hindi' => 'Hindi - India',
		'Hungarian' => 'Hungarian - Hungary',
		'Icelandic' => 'Icelandic - Iceland',
		'Igbo' => 'Igbo - Nigeria',
		'Indonesian' => 'Indonesian - Indonesia',
		'Irish' => 'Irish - Ireland',
		'Italian' => 'Italian - Italy',
		'Japanese' => 'Japanese - Japan',
		'Javanese' => 'Javanese - Indonesia',
		'Kannada' => 'Kannada - India',
		'Kazakh' => 'Kazakh - Kazakhstan',
		'Khmer' => 'Khmer - Cambodia',
		'Kinyarwanda' => 'Kinyarwanda - Rwanda',
		'Korean' => 'Korean - South Korea',
		'Kurdish' => 'Kurdish - Iraq / Turkey',
		'Kyrgyz' => 'Kyrgyz - Kyrgyzstan',
		'Lao' => 'Lao - Laos',
		'Latvian' => 'Latvian - Latvia',
		'Lithuanian' => 'Lithuanian - Lithuania',
		'Luxembourgish' => 'Luxembourgish - Luxembourg',
		'Macedonian' => 'Macedonian - North Macedonia',
		'Malagasy' => 'Malagasy - Madagascar',
		'Malay' => 'Malay - Malaysia',
		'Malayalam' => 'Malayalam - India',
		'Maltese' => 'Maltese - Malta',
		'Maori' => 'Maori - New Zealand',
		'Marathi' => 'Marathi - India',
		'Mongolian' => 'Mongolian - Mongolia',
		'Nepali' => 'Nepali - Nepal',
		'Norwegian' => 'Norwegian - Norway',
		'Odia (Oriya)' => 'Odia (Oriya) - India',
		'Pashto' => 'Pashto - Afghanistan / Pakistan',
		'Persian (Farsi)' => 'Persian (Farsi) - Iran',
		'Polish' => 'Polish - Poland',
		'Portuguese' => 'Portuguese - Portugal / Brazil',
		'Punjabi' => 'Punjabi - India / Pakistan',
		'Romanian' => 'Romanian - Romania',
		'Russian' => 'Russian - Russia',
		'Samoan' => 'Samoan - Samoa',
		'Serbian' => 'Serbian - Serbia',
		'Sesotho' => 'Sesotho - Lesotho / South Africa',
		'Shona' => 'Shona - Zimbabwe',
		'Sindhi' => 'Sindhi - Pakistan / India',
		'Sinhala' => 'Sinhala - Sri Lanka',
		'Slovak' => 'Slovak - Slovakia',
		'Slovenian' => 'Slovenian - Slovenia',
		'Somali' => 'Somali - Somalia',
		'Spanish' => 'Spanish - Spain / Mexico / Latin America',
		'Sundanese' => 'Sundanese - Indonesia',
		'Swahili' => 'Swahili - Kenya / Tanzania',
		'Swedish' => 'Swedish - Sweden',
		'Tajik' => 'Tajik - Tajikistan',
		'Tamil' => 'Tamil - India / Sri Lanka',
		'Tatar' => 'Tatar - Russia',
		'Telugu' => 'Telugu - India',
		'Thai' => 'Thai - Thailand',
		'Tibetan' => 'Tibetan - Tibet / China',
		'Turkish' => 'Turkish - Turkey',
		'Turkmen' => 'Turkmen - Turkmenistan',
		'Ukrainian' => 'Ukrainian - Ukraine',
		'Urdu' => 'Urdu - Pakistan / India',
		'Uzbek' => 'Uzbek - Uzbekistan',
		'Vietnamese' => 'Vietnamese - Vietnam',
		'Welsh' => 'Welsh - Wales / UK',
		'Xhosa' => 'Xhosa - South Africa',
		'Yiddish' => 'Yiddish - Israel',
		'Yoruba' => 'Yoruba - Nigeria',
		'Zulu' => 'Zulu - South Africa',
	],

	];
?>
