<?php

namespace App\Mail;

use Illuminate\Bus\Queueable;
use Illuminate\Mail\Mailable;
use Illuminate\Queue\SerializesModels;
use App\Models\PeopleSalaryIncrement;
use App\Models\Resort;
use App\Models\ProbationLetterTemplate;
use Illuminate\Support\Facades\Storage;
use Carbon\Carbon;

/**
 * Same pattern as PromotionLetterMail/TransferLetterMail — the PDF (with
 * letterhead + per-approver frozen signatures already baked in) is
 * generated by the controller and attached here; this class only builds
 * the short notification email body from the resort's configured template.
 */
class SalaryIncrementLetterMail extends Mailable
{
    use Queueable, SerializesModels;
    public $increment;
    public $pdfPath;
    public $resort;

    public function __construct(PeopleSalaryIncrement $increment, $pdfPath, Resort $resort)
    {
        $this->increment = $increment;
        $this->pdfPath = $pdfPath;
        $this->resort = $resort;
    }

    public function build()
    {
        $template = ProbationLetterTemplate::where('resort_id', $this->increment->resort_id)
            ->where('type', 'salary_increment')
            ->first();

        $subject = $template->subject ?? 'Salary Increment Letter';

        $placeholders = [
            '{{employee_name}}'    => (string) optional($this->increment->employee->resortAdmin)->full_name,
            '{{employee_code}}'    => (string) $this->increment->employee->Emp_id,
            '{{position_title}}'   => (string) optional($this->increment->employee->position)->position_title,
            '{{department_name}}'  => (string) optional($this->increment->employee->department)->name,
            '{{resort_name}}'      => (string) $this->resort->resort_name,
            '{{date}}'             => now()->format('d M Y'),
            '{{previous_salary}}'  => (string) $this->increment->previous_salary,
            '{{new_salary}}'       => (string) $this->increment->new_salary,
            '{{increment_amount}}' => (string) $this->increment->increment_amount,
            '{{increment_type}}'   => (string) $this->increment->increment_type,
            '{{effective_date}}'   => $this->increment->effective_date
                ? Carbon::parse($this->increment->effective_date)->format('d M Y')
                : '',
        ];

        // Same fallback-when-template-has-no-email_body pattern as
        // PromotionLetterMail — the PDF is already attached below either
        // way, this is only the short email body.
        $defaultEmailBody = '<p>Dear {{employee_name}},</p>'
            . '<p>Please find your ' . e($subject) . ' attached.</p>'
            . '<p>Regards,<br>{{resort_name}} HR</p>';
        $emailBodyTemplate = ($template && !empty($template->email_body)) ? $template->email_body : $defaultEmailBody;
        $emailBody = strtr($emailBodyTemplate, $placeholders);

        return $this->view('emails.commonEmail')
            ->with(['mainbody' => $emailBody])
            ->subject($subject)
            ->attach(Storage::path($this->pdfPath), [
                'as' => 'Salary_Increment_Letter_' . (optional($this->increment->employee->resortAdmin)->full_name ?? 'Employee') . '.pdf',
                'mime' => 'application/pdf',
            ]);
    }
}
